name: yaml_formatter
description: A simple command line tool that formats the yaml file and writes back to file.
version: 1.0.0
repository: https://github.com/kalluriramkumar/yaml-formatter

environment:
  sdk: '>=2.12.0 <3.0.0'

executables:
  yaml_formatter: yaml_formatter

dependencies:
  yaml: ^3.1.0
  path: ^1.8.0
  args: ^2.1.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
