name: yaml-formatter-publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Analyze source code
        run: dart analyze

      - name: dry run publish dart package
        uses: k-paxian/dart-package-publisher@master
        with:
          dryRunOnly: true
          credentialJson: ${{ secrets.CREDENTIAL_JSON }}
