name: yaml-formatter-publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Install dependencies
        run: dart pub get

      - name: Analyze source code
        run: dart analyze
      
      - name: add cred
        run: |
          mkdir -p ~/.pub-cache
          echo ${{ secrets.CREDENTIAL_JSON }} > ~/.pub-cache/credential.json
        
      - name: publish
        run: dart pub publish -f

      
          
          
          
